[package]
name = "bytecode"
version.workspace = true
edition.workspace = true

[dependencies]
parser.path = "../parser"
lexer.path = "../lexer"

# only for unit tests
[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
insta = { version = "1.40", features = ["yaml"] }
